<?php
/**
 * CustomerAdditionalAddressDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaTroops
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * troops-evolia-gateway
 *
 * Troops Evolia Gateway API
 *
 * OpenAPI spec version: 1.0.0-troops
 * Contact: ops@troops.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace EvoliaTroops\Model;

use \ArrayAccess;
use \EvoliaTroops\ObjectSerializer;

/**
 * CustomerAdditionalAddressDto Class Doc Comment
 *
 * @category Class
 * @package  EvoliaTroops
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerAdditionalAddressDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CustomerAdditionalAddressDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'address' => 'string',
'postalCode' => 'string',
'city' => 'string',
'country' => 'string',
'legalForm' => 'string',
'insee' => 'string',
'phone' => 'string',
'email' => 'string',
'apeCode' => 'string',
'vatKey' => 'string',
'sirenCode' => 'string',
'siretNic' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'address' => null,
'postalCode' => null,
'city' => null,
'country' => null,
'legalForm' => null,
'insee' => null,
'phone' => null,
'email' => null,
'apeCode' => null,
'vatKey' => null,
'sirenCode' => null,
'siretNic' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address' => 'address',
'postalCode' => 'postalCode',
'city' => 'city',
'country' => 'country',
'legalForm' => 'legalForm',
'insee' => 'insee',
'phone' => 'phone',
'email' => 'email',
'apeCode' => 'apeCode',
'vatKey' => 'vatKey',
'sirenCode' => 'sirenCode',
'siretNic' => 'siretNic'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'address' => 'setAddress',
'postalCode' => 'setPostalCode',
'city' => 'setCity',
'country' => 'setCountry',
'legalForm' => 'setLegalForm',
'insee' => 'setInsee',
'phone' => 'setPhone',
'email' => 'setEmail',
'apeCode' => 'setApeCode',
'vatKey' => 'setVatKey',
'sirenCode' => 'setSirenCode',
'siretNic' => 'setSiretNic'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'address' => 'getAddress',
'postalCode' => 'getPostalCode',
'city' => 'getCity',
'country' => 'getCountry',
'legalForm' => 'getLegalForm',
'insee' => 'getInsee',
'phone' => 'getPhone',
'email' => 'getEmail',
'apeCode' => 'getApeCode',
'vatKey' => 'getVatKey',
'sirenCode' => 'getSirenCode',
'siretNic' => 'getSiretNic'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['postalCode'] = isset($data['postalCode']) ? $data['postalCode'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['legalForm'] = isset($data['legalForm']) ? $data['legalForm'] : null;
        $this->container['insee'] = isset($data['insee']) ? $data['insee'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['apeCode'] = isset($data['apeCode']) ? $data['apeCode'] : null;
        $this->container['vatKey'] = isset($data['vatKey']) ? $data['vatKey'] : null;
        $this->container['sirenCode'] = isset($data['sirenCode']) ? $data['sirenCode'] : null;
        $this->container['siretNic'] = isset($data['siretNic']) ? $data['siretNic'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['address'] === null) {
            $invalidProperties[] = "'address' can't be null";
        }
        if ($this->container['postalCode'] === null) {
            $invalidProperties[] = "'postalCode' can't be null";
        }
        if ($this->container['city'] === null) {
            $invalidProperties[] = "'city' can't be null";
        }
        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        if ($this->container['legalForm'] === null) {
            $invalidProperties[] = "'legalForm' can't be null";
        }
        if ($this->container['phone'] === null) {
            $invalidProperties[] = "'phone' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['apeCode'] === null) {
            $invalidProperties[] = "'apeCode' can't be null";
        }
        if ($this->container['vatKey'] === null) {
            $invalidProperties[] = "'vatKey' can't be null";
        }
        if ($this->container['sirenCode'] === null) {
            $invalidProperties[] = "'sirenCode' can't be null";
        }
        if ($this->container['siretNic'] === null) {
            $invalidProperties[] = "'siretNic' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets postalCode
     *
     * @return string
     */
    public function getPostalCode()
    {
        return $this->container['postalCode'];
    }

    /**
     * Sets postalCode
     *
     * @param string $postalCode postalCode
     *
     * @return $this
     */
    public function setPostalCode($postalCode)
    {
        $this->container['postalCode'] = $postalCode;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city city
     *
     * @return $this
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets legalForm
     *
     * @return string
     */
    public function getLegalForm()
    {
        return $this->container['legalForm'];
    }

    /**
     * Sets legalForm
     *
     * @param string $legalForm legalForm
     *
     * @return $this
     */
    public function setLegalForm($legalForm)
    {
        $this->container['legalForm'] = $legalForm;

        return $this;
    }

    /**
     * Gets insee
     *
     * @return string
     */
    public function getInsee()
    {
        return $this->container['insee'];
    }

    /**
     * Sets insee
     *
     * @param string $insee insee
     *
     * @return $this
     */
    public function setInsee($insee)
    {
        $this->container['insee'] = $insee;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone phone
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets apeCode
     *
     * @return string
     */
    public function getApeCode()
    {
        return $this->container['apeCode'];
    }

    /**
     * Sets apeCode
     *
     * @param string $apeCode apeCode
     *
     * @return $this
     */
    public function setApeCode($apeCode)
    {
        $this->container['apeCode'] = $apeCode;

        return $this;
    }

    /**
     * Gets vatKey
     *
     * @return string
     */
    public function getVatKey()
    {
        return $this->container['vatKey'];
    }

    /**
     * Sets vatKey
     *
     * @param string $vatKey vatKey
     *
     * @return $this
     */
    public function setVatKey($vatKey)
    {
        $this->container['vatKey'] = $vatKey;

        return $this;
    }

    /**
     * Gets sirenCode
     *
     * @return string
     */
    public function getSirenCode()
    {
        return $this->container['sirenCode'];
    }

    /**
     * Sets sirenCode
     *
     * @param string $sirenCode sirenCode
     *
     * @return $this
     */
    public function setSirenCode($sirenCode)
    {
        $this->container['sirenCode'] = $sirenCode;

        return $this;
    }

    /**
     * Gets siretNic
     *
     * @return string
     */
    public function getSiretNic()
    {
        return $this->container['siretNic'];
    }

    /**
     * Sets siretNic
     *
     * @param string $siretNic siretNic
     *
     * @return $this
     */
    public function setSiretNic($siretNic)
    {
        $this->container['siretNic'] = $siretNic;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
