<?php
/**
 * CustomerAdditionalAddressDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaTroops
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * troops-evolia-gateway
 *
 * Troops Evolia Gateway API
 *
 * OpenAPI spec version: 1.0.0-troops
 * Contact: ops@troops.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EvoliaTroops;

/**
 * CustomerAdditionalAddressDtoTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerAdditionalAddressDto
 * @package     EvoliaTroops
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerAdditionalAddressDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerAdditionalAddressDto"
     */
    public function testCustomerAdditionalAddressDto()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "postalCode"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "legalForm"
     */
    public function testPropertyLegalForm()
    {
    }

    /**
     * Test attribute "insee"
     */
    public function testPropertyInsee()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "apeCode"
     */
    public function testPropertyApeCode()
    {
    }

    /**
     * Test attribute "vatKey"
     */
    public function testPropertyVatKey()
    {
    }

    /**
     * Test attribute "sirenCode"
     */
    public function testPropertySirenCode()
    {
    }

    /**
     * Test attribute "siretNic"
     */
    public function testPropertySiretNic()
    {
    }
}
