<?php
/**
 * CustomerResponseDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaTroops
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * troops-evolia-gateway
 *
 * Troops Evolia Gateway API
 *
 * OpenAPI spec version: 1.0.0-troops
 * Contact: ops@troops.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EvoliaTroops;

/**
 * CustomerResponseDtoTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerResponseDto
 * @package     EvoliaTroops
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerResponseDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerResponseDto"
     */
    public function testCustomerResponseDto()
    {
    }

    /**
     * Test attribute "evoliaId"
     */
    public function testPropertyEvoliaId()
    {
    }

    /**
     * Test attribute "troopsId"
     */
    public function testPropertyTroopsId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "shortName"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "legalForm"
     */
    public function testPropertyLegalForm()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "apeCode"
     */
    public function testPropertyApeCode()
    {
    }

    /**
     * Test attribute "vatKey"
     */
    public function testPropertyVatKey()
    {
    }

    /**
     * Test attribute "sirenCode"
     */
    public function testPropertySirenCode()
    {
    }

    /**
     * Test attribute "siretNic"
     */
    public function testPropertySiretNic()
    {
    }

    /**
     * Test attribute "agencies"
     */
    public function testPropertyAgencies()
    {
    }

    /**
     * Test attribute "billingAddress"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "missionAddress"
     */
    public function testPropertyMissionAddress()
    {
    }
}
