<?php
/**
 * CandidateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaTroops
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * troops-evolia-gateway
 *
 * Troops Evolia Gateway API
 *
 * OpenAPI spec version: 1.0.0-troops
 * Contact: ops@troops.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.14
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EvoliaTroops;

use EvoliaTroops\Configuration;
use EvoliaTroops\ApiException;
use EvoliaTroops\ObjectSerializer;

/**
 * CandidateApiTest Class Doc Comment
 *
 * @category Class
 * @package  EvoliaTroops
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CandidateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for create
     *
     * Create new candidate.
     *
     */
    public function testCreate()
    {
    }

    /**
     * Test case for getcandidateByEmail
     *
     * Get candidate by email.
     *
     */
    public function testGetcandidateByEmail()
    {
    }

    /**
     * Test case for getcandidateBydId
     *
     * Get candidate by id (Evolia ID).
     *
     */
    public function testGetcandidateBydId()
    {
    }

    /**
     * Test case for update
     *
     * Update a candidate by ID (Evolia ID).
     *
     */
    public function testUpdate()
    {
    }
}
